### ISSUE TITLE
Diplomacy! (the game)

### ISSUE THREAD

**Issue by pavellishin** [jeffkaufman/nomic#84]
_At some point, we need to admit to ourselves that we're using Github as a vBulletin alternative._

@jeffkaufman, @tnelling, @dchudz and myself have expressed some interest in playing (a possibly Star Trek themed) version of Diplomacy, and this feels like as good of a place as any to talk about that :P

**Comment by jeffkaufman** [comment]
Honestly, that I put a bunch of work into writing that is part of why I'd like to play again...

**Comment by tnelling** [comment]
A couple things about Diplomacy:

1. The idea of Slack was mentioned elsewhere. Maybe Nomic doesn't need Slack, but Slack would be a _fantastic_ way to do a Dip game.
2. Nomic and Dip simultaneously with overlapping players seems like... not the best idea. If we're going to do Dip, let's take a break from Nomic and consider resuming after we finish. Or just do Nomic.
3. I think you need to have played quite a bit of standard Dip before it makes sense to tackle the Star Trek variant. Standard Dip is pretty challenging.
4. @pavellishin asked why I disagreed that the standard Dip map is bad. I'm not sure I understand the objection that the interesting stuff is all in the center - can you be more specific? I'm also not sure what "hard to read" means. I guess the territories are smaller, but they're big enough, and the adjacencies are clear.

**Comment by tnelling** [comment]
Oh wow, I'd completely forgotten about making the icons for DS9!

**Comment by pavellishin** [comment]
> The idea of Slack was mentioned elsewhere. Maybe Nomic doesn't need Slack, but Slack would be a fantastic way to do a Dip game.

I agree! Please don't tempt me into writing a Diplomacy implementation for Slack, not the briar patch, noooooooo...

> Nomic and Dip simultaneously with overlapping players seems like... not the best idea. If we're going to do Dip, let's take a break from Nomic and consider resuming after we finish. Or just do Nomic.

I'd be fine with playing only one at a time; maybe keep Nomic going for a bit so we can implement #77?

> I think you need to have played quite a bit of standard Dip before it makes sense to tackle the Star Trek variant. Standard Dip is pretty challenging.

I'd be fine with spectating a game, tbh. I don't know how that would work with Diplomacy; I could look over one player's shoulder, if I can't be trusted with a Q's eye view :P

> *I guess the territories are smaller, but they're big enough, and the adjacencies are clear.*

They absolutely aren't to me, and I kept making stupid mistakes because it was hard for me to read the map. It's just a very weird layout, from a UX perspective, unless it's intentional - why is there so much wasted space around the edges? Why is Russia huge? I think you could literally chop off the right quarter of the board and lose no information. (Although vague eyeballing suggests that this might turn Armenia into a sliver.)

**Comment by tnelling** [comment]
> They absolutely aren't to me, and I kept making stupid mistakes because it was hard for me to read the map. It's just a very weird layout, from a UX perspective, unless it's intentional - why is there so much wasted space around the edges? Why is Russia huge? I think you could literally chop off the right quarter of the board and lose no information. (Although vague eyeballing suggests that this might turn Armenia into a sliver.)

It sounds like maybe you were just looking at a bad map, Russia being huge aside. Which map/app were you using? I know some of the board game versions are unnecessarily visually noisy, and I think playing on a physical board is actually a pretty bad experience compared to playing using some kind of digital map, because even if the board isn't noisy it's much harder to process the units, topology, and ownership all at once.

I think the reason Russia is huge is pretty obvious (insofar as the game is portraying something based on real history and geography), but as you note re: Armenia, it's about as small as it could be without causing problems elsewhere (see also the small connection between the Norwegian Sea and the Barents).

Unless you're talking about why Russia isn't sub-divided into more territories, in which case I'd just say it's because of map balance concerns. For example, it's not possible for Russia to hold St Petersburg against a northern assault if they don't have a northern navy - BAR + Nwy + Fin + GOB beats Mos + Lvn + StP. If you split Moscow or StP in half, that's no longer true. Similarly, dividing Sevastopol up makes it too safe from Turkey initially, or moves it too far from Moscow or the Balkans, depending on where you divide it. Overall, I think the map is pretty elegantly designed in terms of topology, with the one possible exception being some aspects of Italy.

**Comment by pavellishin** [comment]
I played in person, with a paper map - so maybe that's it. 

I'm definitely not suggesting splitting Russia into more components (_you heretic! RUSSIA STRONK! 🇷🇺 ⭐️_). But as you say, it's annoying to parse things out irl.

Also I kind of zoned out once you started citing specific connections, because I'd have to go and look up the map again, parse it out, etc., etc, and I don't want to unless I commit to playing a game :P I'll take your word for the topological design - it's the human UX element that bugs me.
